# ARS配置参数
env_name: HalfCheetah-v4
timesteps: 500000
seed: 42
n_workers: 16

# ARS特定参数
n_directions: 16
deltas_used: 16
step_size: 0.02
delta_std: 0.03
optimizer_type: multi_scale  # 可选: sgd, adam, zero_order, multi_scale
rollout_length: 1000

# 运行配置
log_interval: 10
save_interval: 100
eval_episodes: 10 