# 比较配置参数
env_name: HalfCheetah-v4
timesteps: 500000
seed: 42
n_workers: 8
parallel_collection: true

# 要比较的算法
algorithms:
  - ppo
  - ms_ppo
  - ddpg
  - ms_ddpg
  - ars

# PPO特定参数
hidden_dim: 1024
actor_lr: 2.0e-4
critic_lr: 1.0e-3
batch_size: 512
ppo_epochs: 5
target_kl: 0.01
ent_coef: 0.01
policy_update_interval: 2048
normalize_states: true

# DDPG特定参数
buffer_size: 1000000
start_steps: 10000
noise_scale: 0.1
collection_interval: 1000

# ARS特定参数
n_directions: 16
deltas_used: 16
step_size: 0.02
delta_std: 0.03
optimizer_type: multi_scale
rollout_length: 1000

# MSZoo优化配置
mszoo_config:
  perturbation_radii: [0.01, 0.02, 0.05]
  population_size: 10
  weight_update_interval: 20
  noise_std: 0.15
  noise_decay: 0.995

# 运行配置
log_interval: 10
save_interval: 100
eval_episodes: 10 