# 实验1：使用较大扰动半径的MSZoo配置

# 基本设置
exp_name: "large_rad_exp"
env_name: HalfCheetah-v4
seed: 42
timesteps: 10000000
algorithms:
  - ms_ppo
  - ms_ddpg
  
# 资源设置
n_workers: 32
parallel_collection: true

# PPO超参数
batch_size: 512
ppo_epochs: 5
target_kl: 0.01
ent_coef: 0.01
policy_update_interval: 2048
normalize_states: true

# DDPG超参数
buffer_size: 10000000
start_steps: 10000
noise_scale: 0.1

# MSZoo配置 - 使用较大的扰动半径
use_mszoo: true
mszoo_config:
  perturbation_radii: [0.05, 0.1, 0.2]  # 较大的扰动半径
  population_size: 10
  weight_update_interval: 20
  noise_std: 0.2                        # 更大的噪声标准差
  noise_decay: 0.99                     # 较慢的衰减率

# 运行配置
log_interval: 10
save_interval: 100
eval_episodes: 10 